@Ecomerce_HostAddress = http://localhost:5139

#Check that api is working or not
GET http://localhost:5139
###


#Check That what is the List Initial Situation
GET http://localhost:5139/api/categories
###

#Check list by ID
GET http://localhost:5139/api/categories/12345678-1234-1234-1234-123456789abc
###


# #Search Value , There C%23 meand C#
# GET http://localhost:5139/api/categories/search?searchValue=C%23
# ###

# #Search Value , 
# GET http://localhost:5139/api/categories/search?searchValue=
# ###


#Create a Manual Data and insert to List
POST http://localhost:5139/api/categories/AddManualData
###


#Pass Manual Data and insert to list
POST http://localhost:5139/api/categories
Content-Type: application/json

{
    "name": "Python",
    "description": "It is a Type of Programming Language"
}

###


#Update Data
PUT http://localhost:5139/api/categories/12345678-1234-1234-1234-123456789abc
Content-Type: application/json

{
    "name": "JavaScripts",
    "description": "Its a Type of Programming Language, Which is most popular to Web Development"
}

###


#Delete Data
DELETE http://localhost:5139/api/categories/12345678-1234-1234-1234-123456789abc

###
